### ISSUE TITLE
Politician + Electoral Map Task List | 2008 Delimitation v1

### ISSUE THREAD

**Issue by vrathi0** [vrathi0/politics_growth#18]
Documentation notes can be found here #16 

- [ ] Processed old pre 2008 electoral map and mapped it to the current map

## Learnings/Notes: 
- Number of electoral district remains unchanged. This is true for both state assembly(AC) and national parliament (PC). 
- Even though number remain unchanged there is a flux as PC and AC might change their status from reserved constituency to non-reserved constituency or vice versa. There are two types of non-reserved constituencies. 
- **Note that the core identification assumption is that this change happens during the assembly term and is unknown to everyone beforehand. As soon as it happens, the prob. of getting reelected changes instantaneously and discontinuously (as I document below).** 
- At this time, I focus on PC. 
- Administrative districts do not change during 2008 delimitation. 
- 1 PC contains district number of ACs. 1 administrative district contains discrete number of ACs. PC can cross admin district boundaries. 

- [ ] Merged with election data for both pre and post period. 

## Learnings/Notes
- Mobility of constituencies across categories. 

GEN to GEN | 330
-- | --
 GEN to RES | 43
RES to GEN | 33
RES to RES | 70

- Incumbent re-election rate | Baseline

 type | incumbent_count | relection_count | relection_rate (%)  
-- | ---- | ---- | --
GEN         |         383        |      140     |        36.6
 RES(SC)        |            72       |        30       |      41.7
RES(ST)         |           31      |         14      |       45.2
NA             |       30          |      0         |     0  

- Incumbent re-election rate | Baseline

 mob_cls | incumbent_count | relection_count | relection_rate (%)  
-- | ---- | ---- | --
GEN to GEN        |         330        |      89     |        27
GEN to RES        |            43       |        0       |      0
RES to GEN         |           33      |         0      |       0
RES to RES             |       70          |      25         |    35.7  
NA.        | 40 | 0| 0

**Comment by vrathi0** [comment]
## Next Steps

There are a few more metrics that can be created, listing them below. 

- [ ] There is more variation in terms of overlap between old PC and new PC; new PC and admin district; if the PC lost any "key" AC; if the PC gained any key "AC". These would be nice to have at hand later on. 
- [ ] Construct a similar mobility metrics for AC, already have all the data processed. 


### More option steps

- [ ] THe 2008 delimitation pdf have AC level detailed demographic tables. These contain total population, backward class population. These can potentially be used to compare marginal AC/PC that got a reserved status to marginal AC/PC that did not get a reserved status. But not clear how it might be immediately useful. 
- [ ] Through an entirely independent process, new administrative districts are also created sporadically. This process is not unexpected, totally intentional and therefore everyone expects and knows the outcome in advance. Regardless, worth keeping in mind in case you can figure out how to use creation of a new administrative district in the empirical strategy.

**Comment by vrathi0** [comment]
## Task List + Update (Jan 13, 2025)

- MP's election does not seem to drive churn at IAS level. Baseline churn is mostly annual. 
- Still some MP-IAS pair seem to have characteristics that are meaningful different than average and that are also correlated with other downstream outcomes (IAS success rate, or upstream MP no_terms). 

- [ ] The OLD TASK LIST IS STILL PENDING. LOOK UP! 
- [ ] **Dimension Reduction**.  Need to construct a new measure that reduces the dimensionality on politician X (both MP and MLA). This is a clean way forward as this new metric should contains all X that might be relevant to measure "how much" politician might be able to influence govt (like party seniority, seasoned, caste, profession, etc).
