### ISSUE TITLE
Outcome measures (Firm level or private Investment) v1

### ISSUE THREAD

**Issue by vrathi0** [vrathi0/politics_growth#20]
Very little work has been done here.  Outcome measures are likely to come from here.

### Task List

- [ ] Make a list of potentially useful data and include small notes. 
- [ ] Process CMIE project level data and merge it with election data geography. 
         
- [ ] Merge MCA firm entry data with election data.

**Comment by vrathi0** [comment]
##  CMIE CAPex task list

### Categorizing the projects

- [ ] **Along Industry**: There are around 134 unique industry/codes and after top 24, rest have less than 1% contribution. 
- [ ] **Along Ownership**: Private/Corporate/State Govt/Central Govt/PSU
- [ ] **Along Nature of Proj**" New/expansion. 

Can add more categories if you find. But the idea here along the following lines: Suppose you find an increase in flow at any point, it would be relavant to know what kind of flow so as to interpret it. Further even without an increase heterogeneity along these dimensions would be very useful to explore. **Am I missing something here? this feels a bit unsatisfactory**


### Categorizing the Events

- [ ] To improve the quality of link with the bureaucracy, you need to improve the classification of events. Currently rank1 events are a bit too broad. 
- [ ] Ideally. If your point is regarding bureaucracy, then the events related to bureaucracy should show higher effect than events that do not involve bureucracy (maybe zero effect here).

**Comment by vrathi0** [comment]
## Updated Task List (Jan 13, 2025)

- [ ] Revise project level classification. The goal here is to construct good measures that are usable in the experimental framework. The prior is that measures should clearly highlight characteristic that are both: (A) important/salient, (B) correlated to politics/bureaucracy in some way. 
- [ ] Write to Anirban Sen or Gaurav to see if possible to get the politician-firm connection data.
